apiVersion: v2
name: ops-tools
version: 1.2.1
description: Helm chart for operations tools and infrastructure items
dependencies:
  # prerequisite: kubectl -n kube-system create secret generic hcloud --from-literal=token=<hcloud API token>
  - name: hcloud-cloud-controller-manager
    repository: https://charts.hetzner.cloud
    version: 1.19.x

  # allows using Hetzner Cloud Volumes as persistent volumes
  - name: hcloud-csi
    repository: https://charts.hetzner.cloud
    version: 2.6.x

  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.9.x
    condition: ingress-nginx.enabled
  
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.13.x
    condition: cert-manager.enabled